FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y git && \
    pip install --no-cache-dir pip-tools && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# default env variables
ENV BRANCH=main
ENV PATH_TO_MAIN=app.py
ENV REPO_URL=https://gitlab.com/username/repo.git

ENTRYPOINT ["/entrypoint.sh"]
