# Base image
FROM python:3.11-slim

WORKDIR /app

# Install git and pip
RUN apt-get update && \
    apt-get install -y git && \
    pip install --no-cache-dir pip-tools && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy base requirements
COPY requirements.txt .

# Install base packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set default env variables
ENV BRANCH=main
ENV PATH_TO_MAIN=app.py
ENV REPO_URL=https://gitlab.com/username/repo.git

ENTRYPOINT ["/entrypoint.sh"]
