apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
spec:
  containers:
    - name: debug
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: itsmsb-code-repo
          mountPath: /itsmsb-code-repo
  volumes:
    - name: itsmsb-code-repo
      persistentVolumeClaim:
        claimName: itsmsb-code-repo
